graph LR
    A[220 V AC] --> B[TRANSFORMER]
    B --> C[RECTIFIER DIODE]
    C --> D[FILTER CAPACITOR]
    D --> E[OUTPUT]

    style A fill:#64e5ef,stroke:#000,stroke-width:2px
    style B fill:#64e5ef,stroke:#000,stroke-width:2px
    style C fill:#64e5ef,stroke:#000,stroke-width:2px
    style D fill:#64e5ef,stroke:#000,stroke-width:2px
    style E fill:#64e5ef,stroke:#000,stroke-width:2px
